### PR TITLE
Sameer/feat/About us section

### PR DESCRIPTION
**Pull request by Sameer01-01**
completed the about us section according to the figma design which is responsive for laptop and almost every mobile device size.

## Laptop
Screenshot 2024-11-15 040842

## Different screen size mobile devices 
Screenshot 2024-11-15 040903

Screenshot 2024-11-15 040919

Screenshot 2024-11-15 040937

### CODE REVIEW

**Review by djdiptayan1 — APPROVED** [review]
LGTM

**Comment by aditionkar** [comment]
LGTM

**Review by aditionkar — APPROVED** [review]

**Comment by djdiptayan1** [comment]
@Sameer01-01 fix conflicts, then will be merged

**Comment by Sameer01-01** [comment]
> @Sameer01-01 fix conflicts, then will be merged

I've made the changes regarding the conflicts.

**Comment by akagtag** [comment]
fix this, u hv imported about us twice. Delete the about us folder just use the file inside the component.
image

**Comment by Sameer01-01** [comment]
> fix this, u hv imported about us twice. Delete the about us folder just use the file inside the component. image

I've done the changes.

**Review by akagtag — APPROVED** [review]
LGTM

**Pull request merged**
